### ISSUE TITLE
Add ability to download assets from server

### ISSUE THREAD

**Issue by b-turchyn** [b-turchyn/EpicQuestClient#9]
- [ ] #10 - Retrieve list of patches from server
- [ ] #11 - Verify integrity of patches
- [ ] #12 - Extract patches to proper directory (configurable directory)
- [ ] #13 - Verify integrity of all files for client (some sort of manifest with checksums)
- [ ] #14 - Configure app to allow reading of local assets without security errors being thrown (Phaser limitation)
